# app custom Makefile

# Docker repo & image name without version
IMAGE            ?= nginx
# Docker image version
IMAGE_VER        ?= 1.19.4-alpine
# Hostname for external access
APP_SITE         ?= site.dev.lan
# Overwrite dcape-compose.yml
DCAPE_APP_DC_YML  = dcape-compose.yml

# ------------------------------------------------------------------------------
# app custom config

PERSIST_FILES     = html enable404.sh gzip.conf realip.conf
APP_ACME_DOMAIN  ?= www.$(APP_SITE)

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)

# Certificate domain (www.APP_SITE or *.APP_SITE)
APP_ACME_DOMAIN=$(APP_ACME_DOMAIN)
endef


# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE  ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif
